Fix introduction ru
twirl/The-API-Book pull request #20
Opened 2021-10-28 07:11 UTC by Callista-del-Mar

2021-10-28 20:44 UTC, twirl requested changes

2021-10-28 20:44 UTC, twirl commented on src/ru/clean-copy/01-Введение/01.md
> +Книга*, которую вы держите в руках, состоит из введения и трех больших разделов.
А к чему тут "*"?

2021-10-28 20:44 UTC, twirl commented on src/ru/clean-copy/01-Введение/02.md
> +Прежде чем говорить о разработке API, необходимо для начала договориться о том, что же такое API. Энциклопедия скажет нам, что API — это программный интерфейс приложений. Это точное определение, но б
«Правила» рекомендуют ставить точку внутри скобок, если она относится к мысли внутри скобок же
http://new.gramota.ru/biblio/readingroom/rules/165-oszp

2021-10-28 20:44 UTC, twirl commented on src/ru/clean-copy/01-Введение/06.md
> +Для составных частей сущности, к сожалению, достаточно нейтрального термина нам придумать не удалось, поэтому мы используем слова: «поля» и «методы».
Гм, нет, получается другой смысл. Мне хотелось написать «поэтому мы используем термины "поля" и "методы"», но «термины» в предложении уже есть. Возможно, стоит наоборот переставить.

2021-11-16 07:33 UTC, merged

2021-11-20 15:58 UTC, zaraysky commented on src/ru/clean-copy/01-Введение/06.md
> +Для составных частей сущности, к сожалению, достаточно нейтрального термина нам придумать не удалось, поэтому мы используем слова: «поля» и «методы».
"Слова" можно вовсе опустить. Смысл не изменится.